#!/bin/bash

yellow='\033[1;33m'   # Amarelo - para avisos.
nocolor='\033[0m' # Reseta a cor para o padrão do terminal.

echo -e "${yellow}CPU governor in use:${nocolor}"
cpupower frequency-yellow | grep -E "ondemand|schedutil|performance|userspace"
echo -e "${yellow}CPU governor in use (per thread):${nocolor}"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo -en "${yellow}\nPress ENTER to go back to the MENU or CTRL+C to finish.${nocolor}"
read
