#!/bin/bash

yellow='\033[1;33m'
nocolor='\033[0m'

clear
echo -e "${yellow}Esses são os scripts presentes em \"$HOME/.local/bin\".${nocolor}"
ls -1 "$HOME/.local/bin/" | grep -vx "myscripts"

echo -en "${yellow}\nPress ENTER to go back to the MENU or CTRL+C to finish.${nocolor}"
read
