#!/bin/bash

# Cores
green='\033[0;32m'
yellow='\033[1;33m'
red='\033[0;31m'
blue='\033[0;36m'
nocolor='\033[0m' # Reseta a cor para o padrão do terminal.

# Função 01 -----------------------------------------------------------------------------#

check_enabled () {

if systemctl is-enabled $2 --quiet $1 ; then
    echo -e "${green}●${nocolor} Enabled to run on boot."
else
    echo -e "○ Disabled to run on boot."
fi

}

# Função 02 -----------------------------------------------------------------------------#

check_running () {

if systemctl is-active $2 --quiet $1 ; then
    echo -e "${green}●${nocolor} Running."
else
    echo -e "○ Parado."
fi

}

# Execução do script --------------------------------------------------------------------#

clear
echo -e "${yellow}############# SERVIÇOS DO USUÁRIO #############${nocolor}"
echo

echo -e "${blue}File Browser Quantum: ------------------------#${nocolor}"
check_running "filebrowser.service" "--user"
check_enabled "filebrowser.service" "--user"
echo

echo -e "${blue}Tailscale: -----------------------------------#${nocolor}"
check_running "tailscaled.service"
check_enabled "tailscaled.service"
echo

echo -e "${blue}CPU Power: -----------------------------------#${nocolor}"
check_running "cpupower-performance.service"
check_enabled "cpupower-performance.service"
echo

echo -en "${yellow}\nPress ENTER to go back to the MENU or CTRL+C to finish.${nocolor}"
read
