#!/bin/bash

set -u

blue='\033[0;36m'
green='\033[0;32m'
yellow='\033[1;33m'
red='\033[0;31m'
nocolor='\033[0m'

remote="jedifonseca@100.80.135.72"
remote_ip="100.80.135.72"

documentos1="/mnt/dados/Documentos/"
imagens1="/mnt/dados/Imagens/"
musicas1="/mnt/dados/Músicas/"
midias1="/mnt/dados/Mídias/"
jogos_android1="/mnt/dados/Jogos/Jogos Android/"
arquivos_de_jogos1="/mnt/dados/Jogos/Arquivos de Jogos/"
videos_diversos1="/mnt/dados/Vídeos/Diversos/"
videos_friends1="/mnt/dados/Vídeos/Friends/"
videos_shows1="/mnt/dados/Vídeos/Shows/"

documentos2="/mnt/Backup/Documentos/"
imagens2="/mnt/Backup/Imagens/"
musicas2="/mnt/Backup/Músicas/"
midias2="/mnt/Backup/Mídias/"
jogos_android2="/mnt/Backup/Jogos/Jogos Android/"
arquivos_de_jogos2="/mnt/Backup/Jogos/Arquivos de Jogos/"
videos_diversos2="/mnt/Backup/Vídeos/Diversos/"
videos_friends2="/mnt/Backup/Vídeos/Friends/"
videos_shows2="/mnt/Backup/Vídeos/Shows/"

gdriveremote="gdrive"
documentos3="$HOME/.mnt/NAS/mnt/dados/Documentos/"
imagens3="$HOME/.mnt/NAS/mnt/dados/Imagens/"
imagens_gdrive="18uxD5feGq2Aul8GsDdRmas4MmNPHaiJC"
documentos_gdrive="1r9MjQEYrFilu-qJneK24_NaqxjRU3--K"

# ------------------------------------------------------------------------------------------------------------------------

safety_checks () {

clear

echo -e "${blue}Testando conexão com o Serverus...${nocolor}"

if ping -c3 -W3 $remote_ip > /dev/null; then
    echo -e "${green}\nConexão OK!${nocolor}"
else
    echo -e "${red}\nServidor não responde!${nocolor}"
    exit 3
fi

mountpoint -q /mnt/Backup || { echo -e "${red}Backup não montado!${nocolor}"; exit 1; }
mountpoint -q "$HOME/.mnt/NAS" || { echo -e "${red}NAS não montado!${nocolor}"; exit 2; }

}

# ------------------------------------------------------------------------------------------------------------------------

sinc_local () {

echo -e "${yellow}\nSincronizando os Documentos...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$documentos1" "$documentos2"

echo -e "${yellow}\nSincronizando as Imagens...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$imagens1" "$imagens2"

echo -e "${yellow}\nSincronizando as Músicas...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$musicas1" "$musicas2"

echo -e "${yellow}\nSincronizando as Mídias...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$midias1" "$midias2"

echo -e "${yellow}\nSincronizando os Jogos de Android...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$jogos_android1" "$jogos_android2"

echo -e "${yellow}\nSincronizando os Arquivos de Jogos...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$arquivos_de_jogos1" "$arquivos_de_jogos2"

echo -e "${yellow}\nSincronizando os Vídeos Diversos...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$videos_diversos1" "$videos_diversos2"

echo -e "${yellow}\nSincronizando os Vídeos de Friends...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$videos_friends1" "$videos_friends2"

echo -e "${yellow}\nSincronizando os Vídeos de Shows...${nocolor}"
rsync -ah --partial --info=progress2 --stats --delete "$remote:$videos_shows1" "$videos_shows2"

}

# ------------------------------------------------------------------------------------------------------------------------

sinc_remoto () {

echo -e "${yellow}\nSincronizando os Documentos com o Google Drive...${nocolor}"
rclone sync "$documentos3" "$gdriveremote,root_folder_id=$documentos_gdrive:" -P

echo -e "${yellow}\nSincronizando as Imagens com o Google Drive...${nocolor}"
rclone sync "$imagens3" "$gdriveremote,root_folder_id=$imagens_gdrive:" -P

}

# ------------------------------------------------------------------------------------------------------------------------

safety_checks
sinc_local
sinc_remoto
