#!/bin/bash

# Variáveis

yellow='\033[1;33m'
red='\033[0;31m'
blue='\033[0;36m'
nocolor='\033[0m'

remote="jedifonseca@100.70.152.117"

imagens1="/mnt/Arquivo/Imagens/"
imagens2="/mnt/dados/Imagens/"
documentos1="/mnt/Arquivo/Documentos/"
documentos2="/mnt/dados/Documentos/"
videos1="/mnt/Arquivo/Vídeos/Diversos/"
videos2="/mnt/dados/Vídeos/Diversos/"
musicas1="/mnt/Arquivo/Músicas/"
musicas2="/mnt/dados/Músicas/"
arqdejogos1="/mnt/Arquivo/Jogos/Arquivos de Jogos/"
arqdejogos2="/mnt/dados/Jogos/Arquivos de Jogos/"
jogosand1="/mnt/Arquivo/Jogos/Android/"
jogosand2="/mnt/dados/Jogos/Android/"

gdriveremote="gdrive"
imagens_gdrive="18uxD5feGq2Aul8GsDdRmas4MmNPHaiJC"
documentos_gdrive="1r9MjQEYrFilu-qJneK24_NaqxjRU3--K"

# Execução

sinc_homelab () {

rsync -avP --delete "$imagens1" "$remote:$imagens2"

echo -e -n "${yellow}Imagens sincronizadas! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rsync -avP --delete "$documentos1" "$remote:$documentos2"

echo -e -n "${yellow}Documentos sincronizados! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rsync -avP --delete "$videos1" "$remote:$videos2"

echo -e -n "${yellow}Vídeos sincronizados! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rsync -avP --delete "$musicas1" "$remote:$musicas2"

echo -e -n "${yellow}Músicas sincronizadas! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rsync -avP --delete "$arqdejogos1" "$remote:$arqdejogos2"

echo -e -n "${yellow}Arquivos de Jogos sincronizados! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rsync -avP --delete "$jogosand1" "$remote:$jogosand2"

}

sinc_remoto () {

rclone sync "$imagens1" "$gdriveremote,root_folder_id=$imagens_gdrive:" -P

echo -e -n "${yellow}Imagens sincronizadas! Pressione ENTER para continuar ou CTRL+C para parar.${nocolor}"
read -r

rclone sync "$documentos1" "$gdriveremote,root_folder_id=$documentos_gdrive:" -P

}

while true; do

	clear
	
	echo -e "${blue}================= SINCRONIZAÇÃO DE ARQUIVOS =================${nocolor}"
	echo "1) Sincronizar Imagens"
	echo "2) Sincronizar Documentos"
	echo "3) Sincronizar Vídeos"
	echo "4) Sincronizar Músicas"
	echo "5) Sincronizar Arquivos de Jogos"
	echo "6) Sincronizar Jogos de Android"
	echo "7) Sincronizar Tudo"
	echo -e "${blue}-------------------------------------------------------------${nocolor}"
	echo "8) Sincronizar Imagens (Google Drive)"
	echo "9) Sincronizar Documentos (Google Drive)"
	echo "10) Sincronizar Tudo (Google Drive)"
	echo
	echo -en "${yellow}Escolha uma opção: ${nocolor}"
	read -r opcao
	
	case "$opcao" in
		1) rsync -avP --delete "$imagens1" "$remote:$imagens2" ;;
		2) rsync -avP --delete "$documentos1" "$remote:$documentos2" ;;
		3) rsync -avP --delete "$videos1" "$remote:$videos2" ;;
		4) rsync -avP --delete "$musicas1" "$remote:$musicas2" ;;
		5) rsync -avP --delete "$arqdejogos1" "$remote:$arqdejogos2" ;;
		6) rsync -avP --delete "$jogosand1" "$remote:$jogosand2" ;;
		7) sinc_homelab ;;
		8) rclone sync "$imagens1" "$gdriveremote,root_folder_id=$imagens_gdrive:" -P ;;
		9) rclone sync "$documentos1" "$gdriveremote,root_folder_id=$documentos_gdrive:" -P ;;
		10) sinc_remoto ;;
		*) echo -en "${red}\nOpção inválida!\n\n${nocolor}"  ;;
	esac
	
	echo -e -n "${yellow}Pressione ENTER para voltar ao menu ou CTRL+C para encerrar o script.${nocolor}"
	read -r
	
done
