#!/bin/bash

# Definição de cores.
GREEN='\033[0;32m' # Verde
BLUE='\033[0;36m'  # Ciano.
YELLOW='\033[1;33m'   # Amarelo.
RED='\033[0;31m' # Vermelho.
NOCOLOR='\033[0m' # Reseta a cor para o padrão do terminal.

#################################################
### ENTRADA DE DADOS E DEFINIÇÃO DE VARIÁVEIS ###
#################################################

echo -e "Script para descobrir o IP de VMs do VirtualBox."
echo -e "Para esse script funcionar, a máquina virtual deverá estar ligada."
echo -e "${YELLOW}Pressione ENTER para continuar ou CTRL+C para cancelar. ${NOCOLOR}"
read

# Entrada de dados interativa.
while [ -z "$VMNAME" ]; do

    echo -e "${YELLOW}--- Entrada de Dados (Campo Obrigatório) ---${NOCOLOR}"
    read -p "Digite o nome da VM: " VMNAME

    if [ -z "$VMNAME" ]; then
        echo -e "\n${RED}ERRO: O nome da VM precisa ser preenchido!${NOCOLOR}\n"
        VMNAME=""
    fi
done

echo -e "\nO nome da VM ${BLUE}\"$VMNAME\"${NOCOLOR} foi definido com sucesso!\n"

# Descobrindo o IP da VM:
VMIP=$(VBoxManage guestproperty get "$VMNAME" "/VirtualBox/GuestInfo/Net/0/V4/IP" | awk '{print $2}')
echo -e "O IP da VM ${BLUE}$VMNAME${NOCOLOR} é:      ${BLUE}$VMIP${NOCOLOR}"
echo -e "\n${YELLOW}Script Encerrado!${NOCOLOR}"
