#!/bin/bash

blue='\033[0;36m'
green='\033[0;32m'
yellow='\033[1;33m'
red='\033[0;31m'
nocolor='\033[0m'

sudo -v
while true; do sudo -v; sleep 60; done &
sudo_pid=$!
trap "kill $sudo_pid" EXIT

# ---------------------------------------------------------------------------- #

apt_update () {

command -v apt-get > /dev/null || return 0

echo -e "${yellow}\nAtualizando os repositórios do sistema...${nocolor}"
sudo apt-get update

echo -e "${yellow}\nAtualizando o sistema...${nocolor}"
sudo apt-get full-upgrade -y

}

# ---------------------------------------------------------------------------- #

dnf_update () {

command -v dnf > /dev/null || return 0

echo -e "${yellow}\nAtualizando o sistema...${nocolor}"
sudo dnf upgrade -y

}

# ---------------------------------------------------------------------------- #

flatpak_update () {

command -v flatpak > /dev/null || return 0

echo -e "${yellow}\nAtualizando os aplicativos em flatpak...${nocolor}"
sudo flatpak upgrade -y --noninteractive --system
flatpak upgrade -y --noninteractive --user

}

# ---------------------------------------------------------------------------- #

snap_update () {

command -v snap > /dev/null || return 0

echo -e "${yellow}\nAtualizando os aplicativos em Snap...${nocolor}"
sudo snap refresh

}

# ---------------------------------------------------------------------------- #

apt_update
dnf_update
flatpak_update
snap_update

echo -e "${green}\nScript finalizado!${nocolor}"

